### ISSUE TITLE
Complex PromQL expressions

### ISSUE THREAD

**Issue by ocervell** [pabluk/pygments-promql#4]
Hiyah,

does this packages support more complex PromQL expressions ?

I tried with one but the label set is not highlighted properly.

See the following for an example:
![Screenshot 2021-04-22 at 18 27 31](https://user-images.githubusercontent.com/9629314/115750555-9419b000-a398-11eb-9068-977bf4abd3d5.png)

**Comment by pabluk** [comment]
Hi @ocervell, it should also work with that kind of complex expressions.
In any case your expression seems to be a good test case, could you please paste a text version of it? I would like to included in the test suite and fix the output.

Thanks for report it :+1:

**Comment by pabluk** [comment]
I confirm there's a bug, I was able see it using this fragment of your expression:

```
(sum(rate(metric_test_app{app="turtle",proc="web"}[2m])) by(node))
```
and I opened a pull request to fix it.

Here's an example of the output before:

![test-nok](https://user-images.githubusercontent.com/161046/115777724-f339ed80-a3b5-11eb-8cad-d77fa852b716.png)

and after the fix from #5:

![test-ok](https://user-images.githubusercontent.com/161046/115777783-03ea6380-a3b6-11eb-82f8-cc2bc205b188.png)

*note:* those example were generated using
```shell
pygmentize -f png -O "line_numbers=False,style=monokai" -o example.png example.promql
```


I'll wait for your full text PromQL expression to test it before merging this fix.

**Comment by ocervell** [comment]
Hi @pabluk,

Thanks for the swift response !

Here is the full expression:

```
(sum(rate(metric_test_app{app='turtle',proc='web',vendor=~'vendor.',status=~'(4|5)..'}[2m])) by(node)) or (sum(rate(metric_test_app{app='turtle',proc='web',vendor=~'vendor.'}[2m])) by(node)-sum(rate(metric_test_app{app='turtle',proc='web',vendor=~'vendor.',status!~'(4|5)..'}[2m])) by(node))/sum(rate(metric_test_app{app='turtle',proc='web',vendor=~'vendor.',status!~'(4|5)..'}[2m])) by(node)*100",
```

**Comment by pabluk** [comment]
Great! the output of the full expression looks better now
![test4](https://user-images.githubusercontent.com/161046/115863263-836b4780-a435-11eb-8223-55ccb5e55cce.png)

by the way, your full expression allowed me to find out and [fix a typo on a regexp](https://github.com/pabluk/pygments-promql/pull/5/commits/3e0e3f866ebfa7e19d885384081a49cd3384603a).

I'll merge the PR and publish a new release asap.

Thanks again for helping out to improve this PromQL lexer!

**Comment by pabluk** [comment]
The new release [0.0.6 ](https://github.com/pabluk/pygments-promql/releases/tag/0.0.6)is now available on PyPI https://pypi.org/project/pygments-promql/

**Comment by ocervell** [comment]
Perfect ! Thanks a lot :)
